const Car = require('./models/Car');

const cars = [
  {
    name: 'Porsche 911 Carrera',
    brand: 'Porsche',
    type: 'Sports',
    pricePerDay: 350,
    seats: 2,
    transmission: 'PDK',
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    power: 379,
    topSpeed: 182,
    zeroToSixty: 3.5,
    description: 'The Porsche 911 Carrera blends legendary sports-car performance, precision engineering, and an iconic presence.',
    images: [
      'cars/porsche/exterior.avif',
      'cars/porsche/Interior.avif',
      'cars/porsche/Back.jpg',
    ],
    features: ['Premium Insurance', '24/7 Roadside Assist', 'Sport Chrono Package', 'In-car Wi-Fi'],
    rentals: 128,
  },
  {
    name: 'Polestar 2 Long Range',
    brand: 'Polestar',
    type: 'Electric',
    pricePerDay: 145,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    drivetrain: 'AWD',
    power: 408,
    topSpeed: 127,
    zeroToSixty: 4.5,
    description: 'Luxurious electric performance with cutting-edge design, long-range capability, and advanced tech inside.',
    images: [
      'cars/polestar/exterior.jpg',
      'cars/polestar/Interior.webp',
      'cars/polestar/Back.jpg',
    ],
    features: ['Fast Charging', 'Premium Sound', 'Advanced Driver Assistance', 'Climate Control'],
    rentals: 92,
  },
  {
    name: 'Lucid Air Grand Touring',
    brand: 'Lucid',
    type: 'Electric',
    pricePerDay: 295,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    drivetrain: 'RWD',
    power: 620,
    topSpeed: 168,
    zeroToSixty: 3.9,
    description: 'High-end electric luxury with a spacious interior, long-range capability, and blistering acceleration.',
    images: [
      'cars/lucid/exterior.jpg',
      'cars/lucid/Interior.avif',
      'cars/lucid/Back.avif',
    ],
    features: ['Luxury Interior', 'Adaptive Cruise Control', 'Panoramic Roof', 'Wireless Charging'],
    rentals: 76,
  },
  {
    name: 'BMW M4 Competition',
    brand: 'BMW',
    type: 'Sports',
    pricePerDay: 320,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    power: 503,
    topSpeed: 180,
    zeroToSixty: 3.8,
    description: 'A high-performance coupe with sharp handling, aggressive styling, and a track-ready character.',
    images: [
      'cars/bmw/exterior.jpg',
      'cars/bmw/Interior.webp',
      'cars/bmw/Back.webp',
    ],
    features: ['Track Mode', 'Carbon Fiber', 'Heads-up Display', 'M Sport Suspension'],
    rentals: 84,
  },
  {
    name: 'Mercedes-AMG GT',
    brand: 'Mercedes',
    type: 'Luxury',
    pricePerDay: 280,
    seats: 4,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    power: 469,
    topSpeed: 189,
    zeroToSixty: 4.0,
    description: 'A luxurious grand tourer with elegant styling, powerful performance, and premium comfort.',
    images: [
      'cars/mercedes/exterior.avif',
      'cars/mercedes/Interior.avif',
      'cars/mercedes/Back.webp',
    ],
    features: ['Comfort Package', 'Premium Audio', 'Ambient Lighting', 'Advanced Safety Suite'],
    rentals: 63,
  },
  {
    name: 'Range Rover Evoque',
    brand: 'Range Rover',
    type: 'SUV',
    pricePerDay: 410,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    drivetrain: 'AWD',
    power: 296,
    topSpeed: 143,
    zeroToSixty: 6.8,
    description: 'A stylish and capable SUV that combines luxury, comfort, and off-road poise in a compact package.',
    images: [
      'cars/range-rover/exterior.webp',
      'cars/range-rover/Interior.avif',
      'cars/range-rover/Back.jpg',
    ],
    features: ['Terrain Response', 'Panoramic Roof', 'Luxury Leather', 'Premium Safety'],
    rentals: 47,
  },
];

async function seedCars() {
  const count = await Car.countDocuments();
  if (count === 0) {
    await Car.create(cars);
    console.log('Seeded car inventory.');
  }
}

module.exports = seedCars;
